vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    poster_file:
      uri_prefix: /uploads/images/posters
      upload_destination: "%upload_directory_program%"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    avatar_file:
      uri_prefix: /uploads/images/avatars
      upload_destination: "%upload_directory_actor%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
